name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
